apiVersion: v1
kind: Service
metadata:
        name: psweb
spec:
    selector:
            env: staging
            version: v1
            projet: devops-training
    type: NodePort
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
