apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2022-03-05T13:20:02Z","generation":1,"labels":{"app":"pswebapp"},"name":"pswebapp","namespace":"default","resourceVersion":"4303","uid":"5c4cabf1-62bf-4522-8854-f93a0d04891e"},"spec":{"progressDeadlineSeconds":600,"replicas":5,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"pswebapp"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"pswebapp"}},"spec":{"containers":[{"image":"imejri/psweb:21","imagePullPolicy":"IfNotPresent","name":"psweb","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2022-03-05T13:20:02Z","lastUpdateTime":"2022-03-05T13:20:30Z","message":"ReplicaSet \"pswebapp-5f8f9f976f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-03-05T13:23:09Z","lastUpdateTime":"2022-03-05T13:23:09Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2022-03-05T13:20:02Z"
  generation: 3
  labels:
    env: develop
    projet: devops-training
  name: pswebapp
  namespace: default
  resourceVersion: "5407"
  uid: 5c4cabf1-62bf-4522-8854-f93a0d04891e
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      env: develop
      projet: devops-training
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
         env: develop
         projet: devops-training
    spec:
      containers:
      - image: imejri/psweb:21
        imagePullPolicy: IfNotPresent
        name: psweb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-03-05T13:27:09Z"
    lastUpdateTime: "2022-03-05T13:27:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-05T13:20:02Z"
    lastUpdateTime: "2022-03-05T13:27:15Z"
    message: ReplicaSet "pswebapp-67c855f986" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
